= The Beginning
:hp-tags: My Story

One of my earliest memories of what would later be considered "genderfluid" was when I was 5. I came running out my cousin's bedroom wearing her leotard-with-tutu and called out to the my cousin "When you pass this down, can I have it?". I was laughed out of the room by her mother, my aunt. 

I was ashamed that I had done something wrong, but I didn't know what I had done. Tutus were apparently off limits to me, despite the fact that clothes were definitely handed down from my older sister to my older cousins. I thought that meant that I could be next in line for the sparkly-pink thing. Culture, more than any single person, told me that I couldn't have what I wanted. 

My aunt still today tells the story as a bit of comedy at family get togethers: “Hey Will, remember when…” and she laughs. It’s something that we’re all conditioned to think is funny. “Look at the person out of place, not doing what they’re supposed to be doing.” At first we ridicule them, and they either get back in line or persist. If they persist, we poke at them some more or in a different way: “Hey, we just want you to be attractive/successful/desirable.” And they get another chance to either get back in line, or persist. Finally, we either give up trying to make them get back in line, or give up on our relationship with them. 

Ultimately, the people who do this stepping out of line well are the people that we culturally look up to. Usually they’re people who are unusually persistent in their desire to express themselves and we all say “that person is so cool, I want to be just like them” These are the David Bowies of the world. They are the beacons of humanity. Be that person. All it takes is not getting back in line when they tell you to. I’m working on this for myself. 



